code --install-extension anseki.vscode-color
code --install-extension ban.spellright
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cperezabo.routeros-syntax
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension Fr43nk.seito-openfile
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension humao.rest-client
code --install-extension IBM.output-colorizer
code --install-extension ionutvmi.path-autocomplete
code --install-extension ionutvmi.reg
code --install-extension jamiewoodio.cisco
code --install-extension mhutchie.git-graph
code --install-extension mkxml.vscode-filesize
code --install-extension ms-vscode.powershell
code --install-extension myxvisual.vscode-ts-uml
code --install-extension quicktype.quicktype
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension shuworks.vscode-table-formatter
code --install-extension tomoki1207.pdf
code --install-extension usernamehw.errorlens
code --install-extension viablelab.bracket-padder
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yzhang.markdown-all-in-one